In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'D:/Malathi/SEM_4/ML/Telco-Customer-Churn.csv')
data.head(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   
5  9305-CDSKC  Female              0      No         No       8          Yes   
6  1452-KIOVK    Male              0      No        Yes      22          Yes   
7  6713-OKOMC  Female              0      No         No      10           No   
8  7892-POOKP  Female              0     Yes         No      28          Yes   
9  6388-TABGU    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   
5               Yes     Fiber optic             No  ...              Yes   
6               Yes     Fiber optic             No  ...               No   
7  No phone service             DSL            Yes  ...               No   
8               Yes     Fiber optic             No  ...              Yes   
9                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   
5          No         Yes             Yes  Month-to-month              Yes   
6          No         Yes              No  Month-to-month              Yes   
7          No          No              No  Month-to-month               No   
8         Yes         Yes             Yes  Month-to-month              Yes   
9          No          No              No        One year               No   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  
5           Electronic check          99.65         820.5   Yes  
6    Credit card (automatic)          89.10        1949.4    No  
7               Mailed check          29.75         301.9    No  
8           Electronic check         104.80       3046.05   Yes  
9  Bank transfer (automatic)          56.15       3487.95    No  

[10 rows x 21 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [4]:
data = data[data["TotalCharges"]!=' ']
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7032 non-null   object 
 1   gender            7032 non-null   object 
 2   SeniorCitizen     7032 non-null   int64  
 3   Partner           7032 non-null   object 
 4   Dependents        7032 non-null   object 
 5   tenure            7032 non-null   int64  
 6   PhoneService      7032 non-null   object 
 7   MultipleLines     7032 non-null   object 
 8   InternetService   7032 non-null   object 
 9   OnlineSecurity    7032 non-null   object 
 10  OnlineBackup      7032 non-null   object 
 11  DeviceProtection  7032 non-null   object 
 12  TechSupport       7032 non-null   object 
 13  StreamingTV       7032 non-null   object 
 14  StreamingMovies   7032 non-null   object 
 15  Contract          7032 non-null   object 
 16  PaperlessBilling  7032 non-null   object 


In [5]:
data['TotalCharges'] = data['TotalCharges'].astype('float64')
data = data.drop(['customerID'], axis = 1)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7032 non-null   object 
 1   SeniorCitizen     7032 non-null   int64  
 2   Partner           7032 non-null   object 
 3   Dependents        7032 non-null   object 
 4   tenure            7032 non-null   int64  
 5   PhoneService      7032 non-null   object 
 6   MultipleLines     7032 non-null   object 
 7   InternetService   7032 non-null   object 
 8   OnlineSecurity    7032 non-null   object 
 9   OnlineBackup      7032 non-null   object 
 10  DeviceProtection  7032 non-null   object 
 11  TechSupport       7032 non-null   object 
 12  StreamingTV       7032 non-null   object 
 13  StreamingMovies   7032 non-null   object 
 14  Contract          7032 non-null   object 
 15  PaperlessBilling  7032 non-null   object 
 16  PaymentMethod     7032 non-null   object 


In [7]:
objects = data.select_dtypes(include = 'object').columns

In [8]:
for col in objects:
    state = pd.get_dummies(data[col], drop_first = True)
    data = data.join(state, lsuffix = col)
    data = data.drop(col, axis = 1)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   SeniorCitizen                        7032 non-null   int64  
 1   tenure                               7032 non-null   int64  
 2   MonthlyCharges                       7032 non-null   float64
 3   TotalCharges                         7032 non-null   float64
 4   Male                                 7032 non-null   uint8  
 5   YesDependents                        7032 non-null   uint8  
 6   YesPhoneService                      7032 non-null   uint8  
 7   YesMultipleLines                     7032 non-null   uint8  
 8   No phone service                     7032 non-null   uint8  
 9   YesOnlineSecurity                    7032 non-null   uint8  
 10  Fiber optic                          7032 non-null   uint8  
 11  No                            

# Train Test Split

In [10]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x, y, test_size = 0.25,
                                                    random_state = 22)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()

In [14]:
reg.fit(x_train, y_train)
y_pred = reg.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1164  128]
 [ 224  242]]
0.7997724687144482
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1292
           1       0.65      0.52      0.58       466

    accuracy                           0.80      1758
   macro avg       0.75      0.71      0.72      1758
weighted avg       0.79      0.80      0.79      1758



In [16]:
?LogisticRegression

In [17]:
from sklearn.model_selection import GridSearchCV
log_paramsg = {'fit_intercept':[True, False],
             'max_iter':[50, 60, 75, 100, 120]}
log_grid = GridSearchCV(reg, param_grid = log_paramsg, cv = 10, n_jobs = -1)
log_grid.fit(x_test, y_test)

GridSearchCV(cv=10, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'fit_intercept': [True, False],
                         'max_iter': [50, 60, 75, 100, 120]})

In [18]:
print(log_grid.best_params_)
print(log_grid.best_score_)

{'fit_intercept': True, 'max_iter': 50}
0.7986396103896103


In [19]:
from sklearn.model_selection import RandomizedSearchCV
log_paramsr = {'fit_intercept':[True, False],
             'max_iter':[50, 60, 75, 100, 120]}
log_random = RandomizedSearchCV(reg, log_paramsr, cv = 10, n_jobs = -1)
log_random.fit(x_test, y_test)

RandomizedSearchCV(cv=10, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'fit_intercept': [True, False],
                                        'max_iter': [50, 60, 75, 100, 120]})

In [20]:
print(log_random.best_params_)
print(log_random.best_score_)

{'max_iter': 50, 'fit_intercept': True}
0.7986396103896103


# KNN Classifier

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [22]:
?KNeighborsClassifier

In [23]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [24]:
print(knn.predict(x_test))
print(knn.score(x_test, y_test))

[0 0 0 ... 1 0 0]
0.7559726962457338


C:\Users\vinod\miniconda3\envs\mini\lib\site-packages\sklearn\neighbors\_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\vinod\miniconda3\envs\mini\lib\site-packages\sklearn\neighbors\_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be 

In [25]:
knn_paramsg = {'n_neighbors':[2, 4, 5, 6, 8, 10, 20],
              'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute']}
knn_grid = GridSearchCV(knn, knn_paramsg, cv = 10, n_jobs = -1)
knn_grid.fit(x_test, y_test)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 4, 5, 6, 8, 10, 20]})

In [26]:
print(knn_grid.best_params_)
print(knn_grid.best_score_)

{'algorithm': 'auto', 'n_neighbors': 10}
0.7844253246753248


In [27]:
knn_paramsr = {'n_neighbors':[2, 4, 5, 6, 8, 10, 20],
              'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute']}
knn_random = RandomizedSearchCV(knn, knn_paramsg, cv = 10, n_jobs = -1)
knn_random.fit(x_test, y_test)

RandomizedSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [2, 4, 5, 6, 8, 10, 20]})

In [28]:
print(knn_random.best_params_)
print(knn_random.best_score_)

{'n_neighbors': 10, 'algorithm': 'auto'}
0.7844253246753248


# Naive Bayes

In [29]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [30]:
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [31]:
classifier.predict_log_proba(x_test)

array([[ 0.00000000e+00, -4.76313393e+01],
       [ 0.00000000e+00, -6.61499942e+01],
       [-7.16252231e-08, -1.64518185e+01],
       ...,
       [-3.82300074e+00, -2.21046166e-02],
       [ 0.00000000e+00, -6.32265654e+01],
       [-4.75384039e+00, -8.65588735e-03]])

In [32]:
print(confusion_matrix(y_test,y_pred))
print('accuracy:',accuracy_score(y_test,y_pred))

[[783 509]
 [ 68 398]]
accuracy: 0.6717861205915814


In [33]:
print(x_train)

[[ 2.25924029 -0.75056047 -0.62274532 ... -0.52130866  1.38690422
  -0.54184706]
 [-0.44262667 -0.62827393  0.8613512  ...  1.91824935 -0.72103032
  -0.54184706]
 [-0.44262667 -1.07665789  0.96450589 ... -0.52130866 -0.72103032
   1.84553923]
 ...
 [-0.44262667 -1.23970661  0.48200814 ... -0.52130866  1.38690422
  -0.54184706]
 [-0.44262667 -0.26141433 -0.34988453 ...  1.91824935 -0.72103032
  -0.54184706]
 [-0.44262667  0.83916449  1.087626   ... -0.52130866 -0.72103032
  -0.54184706]]


In [34]:
?GaussianNB

In [35]:
nb_paramsg = {'var_smoothing':[1e-1,1e-2,1e-5,1e-8,1e-9,1e-10]}
nb_grid = GridSearchCV(classifier, nb_paramsg, cv = 10, n_jobs = -1)
nb_grid.fit(x_test, y_test)

GridSearchCV(cv=10, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [0.1, 0.01, 1e-05, 1e-08, 1e-09,
                                           1e-10]})

In [36]:
print(nb_grid.best_params_)
print(nb_grid.best_score_)

{'var_smoothing': 1e-05}
0.6507337662337663


# Decision Tree

In [37]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion='entropy', max_depth=4)
tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [38]:
y_pred = tree.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
confusion_matrix(y_test,y_pred)

array([[1206,   86],
       [ 281,  185]], dtype=int64)

In [40]:
accuracy_score(y_test,y_pred)

0.7912400455062572

In [41]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7912400455062572
              precision    recall  f1-score   support

           0       0.81      0.93      0.87      1292
           1       0.68      0.40      0.50       466

    accuracy                           0.79      1758
   macro avg       0.75      0.67      0.68      1758
weighted avg       0.78      0.79      0.77      1758



In [42]:
import pydotplus
from sklearn.tree import export_graphviz
graph = export_graphviz(tree, filled=True, rounded=True)
g = pydotplus.graph_from_dot_data(graph)

g.write_png('telco.png')

True

In [43]:
?DecisionTreeClassifier

In [44]:
dt_paramsg = {'criterion':['gini', 'entropy', 'log_loss'], 'splitter':['random', 'best'],
             'max_features':['auto', 'sqrt', 'log2', None]}
dt_grid = GridSearchCV(tree, dt_paramsg, cv = 10, n_jobs = -1)
dt_grid.fit(x_test, y_test)

GridSearchCV(cv=10,
             estimator=DecisionTreeClassifier(criterion='entropy', max_depth=4),
             n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2', None],
                         'splitter': ['random', 'best']})

In [45]:
print(dt_grid.best_params_)
print(dt_grid.best_score_)

{'criterion': 'entropy', 'max_features': None, 'splitter': 'random'}
0.7861428571428571


In [46]:
dt_paramsr = {'criterion':['gini', 'entropy', 'log_loss'], 'splitter':['random', 'best'],
             'max_features':['auto', 'sqrt', 'log2', None]}
dt_random = RandomizedSearchCV(tree, dt_paramsr, cv = 10, n_jobs = -1)
dt_random.fit(x_test, y_test)

RandomizedSearchCV(cv=10,
                   estimator=DecisionTreeClassifier(criterion='entropy',
                                                    max_depth=4),
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_features': ['auto', 'sqrt', 'log2',
                                                         None],
                                        'splitter': ['random', 'best']})

In [47]:
print(dt_random.best_params_)
print(dt_random.best_score_)

{'splitter': 'random', 'max_features': None, 'criterion': 'log_loss'}
0.7838506493506493


# SVM

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.svm import SVC
clf = SVC()
clf.fit(x_train, y_train)

SVC()

In [49]:
y_pred = clf.predict(x_test)

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1182  110]
 [ 250  216]]
0.7952218430034129
              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1292
           1       0.66      0.46      0.55       466

    accuracy                           0.80      1758
   macro avg       0.74      0.69      0.71      1758
weighted avg       0.78      0.80      0.78      1758



In [51]:
?SVC

In [52]:
    svm_paramsr = {'kernel':['linear', 'poly', 'rbf', 'sigmoid'], 'degree':[1, 2, 3],
                 'gamma':['scale', 'auto']}
    svm_random = RandomizedSearchCV(clf, svm_paramsr, cv = 10, n_jobs = -1)
    svm_random.fit(x_train, y_train)
    print(svm_random.best_params_)
    print(svm_random.best_score_)

{'kernel': 'linear', 'gamma': 'auto', 'degree': 2}
0.801666451037893
