In [1]:
import pandas as pd
import numpy as np
import statistics

In [2]:
from sklearn import datasets
mnist = datasets.load_digits()

In [3]:
data = pd.DataFrame(mnist.data)

In [4]:
cov_mat = data.cov()

In [5]:
cov_mat = cov_mat.values

In [6]:
cov_mat

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.8229975 ,  2.40099498, ..., -0.1598953 ,
         0.09851423, -0.07406182],
       [ 0.        ,  2.40099498, 22.60837352, ..., -1.15544033,
         1.41203571,  0.72988047],
       ...,
       [ 0.        , -0.1598953 , -1.15544033, ..., 34.81734839,
        15.64854441,  2.87558266],
       [ 0.        ,  0.09851423,  1.41203571, ..., 15.64854441,
        16.73258202,  4.72078588],
       [ 0.        , -0.07406182,  0.72988047, ...,  2.87558266,
         4.72078588,  3.46005282]])

In [7]:
values, vectors = np.linalg.eig(cov_mat)

In [8]:
values

array([1.79006930e+02, 1.63717747e+02, 1.41788439e+02, 1.01100375e+02,
       6.95131656e+01, 5.91085249e+01, 5.18845391e+01, 4.40151067e+01,
       4.03109953e+01, 3.70117984e+01, 2.85190412e+01, 2.73211698e+01,
       2.19014881e+01, 2.13243565e+01, 1.76367222e+01, 1.69468639e+01,
       1.58513899e+01, 1.50044602e+01, 1.22344732e+01, 1.08868593e+01,
       1.06935663e+01, 9.58259779e+00, 9.22640260e+00, 8.69036872e+00,
       8.36561190e+00, 7.16577961e+00, 6.91973881e+00, 6.19295508e+00,
       5.88499123e+00, 5.15586690e+00, 4.49129656e+00, 4.24687799e+00,
       4.04743883e+00, 3.94340334e+00, 3.70647245e+00, 3.53165306e+00,
       3.08457409e+00, 2.73780002e+00, 2.67210896e+00, 2.54170563e+00,
       2.28298744e+00, 1.90724229e+00, 1.81716569e+00, 1.68996439e+00,
       1.40197220e+00, 1.29221888e+00, 1.15893419e+00, 9.31220008e-01,
       6.69850594e-01, 4.86065217e-01, 2.52350432e-01, 9.91527944e-02,
       6.31307848e-02, 6.07377581e-02, 3.96662297e-02, 1.49505636e-02,
      

In [9]:
vectors

array([[ 0.        ,  0.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.01730947,  0.01010646, -0.01834207, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.22342883,  0.04908492, -0.12647554, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.08941847, -0.17669712, -0.23208416, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.03659771, -0.01945471, -0.16702656, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.0114685 ,  0.00669694, -0.03480438, ...,  0.        ,
         0.        ,  0.        ]])

In [10]:
PCA = pd.DataFrame()
for i in range(len(vectors)):
    pca = np.dot(data - np.mean(data), vectors[i])
    PCA['PCA'+str(i)] = pca

C:\Users\vinod\miniconda3\envs\mini\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
C:\Users\vinod\miniconda3\envs\mini\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
C:\Users\vinod\miniconda3\envs\mini\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs

In [11]:
PCA

PCA0      PCA1      PCA2       PCA3      PCA4      PCA5      PCA6  \
0    -6.764051  5.408591  8.531134  -7.795688 -3.434522  5.045232 -0.557302   
1     3.235949 -6.836053 -7.053224   8.797642 -3.454722 -4.411983  2.606920   
2     9.235949 -4.787848  2.384902   1.093871 -3.527497 -3.460144 -1.611564   
3     2.235949  5.438718  2.926029   0.645495  5.644645  2.479638 -4.491135   
4    -2.764051  3.523895 -4.185530  -1.367776  3.615336 -8.990784 -1.094314   
...        ...       ...       ...        ...       ...       ...       ...   
1792  2.235949  5.049557  7.566560 -10.205756 -0.130710  1.990960 -0.411646   
1793 -0.764051 -4.060928  3.100846  -6.924547 -2.358627  9.835542  0.126675   
1794 -0.764051 -5.866175 -5.824651   7.470718  1.036081 -3.464641 -0.819296   
1795  5.235949  4.849160  4.647019  -1.892375 -1.656391  1.874377  5.652070   
1796  5.235949  0.703220  3.880055   3.316728  5.271122  2.069932 -2.723359   

          PCA7      PCA8      PCA9  ...     PCA54     PCA55     PCA56  \
0     2.049375 -0.158506 -3.223549  ...  2.168115 -1.030312 -1.613632   
1    -1.962075  0.090140  4.725976  ... -5.551224  1.999260  3.219337   
2     2.808864 -0.662580 -3.346196  ...  5.247649  1.803462 -1.684576   
3    -1.067041 -0.107439  3.304902  ... -6.401007  0.340394  1.221948   
4    -3.698355 -0.946508 -8.554170  ... -2.574779  0.457865  3.228682   
...        ...       ...       ...  ...       ...       ...       ...   
1792 -2.827268 -0.034393  2.987020  ...  1.161620 -1.647312  2.404959   
1793  1.986381  0.259441 -5.325902  ...  3.953824 -1.440508  2.332278   
1794  3.270184 -0.219284 -4.941448  ... -1.227515 -1.077078  0.671264   
1795 -3.026601 -0.143864  1.891329  ... -1.827179 -1.761691  4.042305   
1796  3.134977  0.083252 -4.055744  ... -1.153935 -9.642900  2.496187   

         PCA57     PCA58     PCA59     PCA60     PCA61     PCA62      PCA63  
0     0.174764 -1.869844  3.568894  1.027979 -6.062303 -1.465545  -1.718793  
1     1.203285  4.783324 -1.089862  1.256368  3.482531  3.746668   2.762677  
2     4.623693  4.389829 -8.228628  3.883139  9.743586  1.207668   5.675629  
3    -2.317728 -8.585752  6.640792 -7.136755 -3.846522  5.882443   4.627573  
4    -5.315708  4.674444  2.528760  4.353020  1.721549  8.773279  -5.531586  
...        ...       ...       ...       ...       ...       ...        ...  
1792  2.138891 -1.093946  0.159986  2.127678  0.726658 -3.907563  -3.357611  
1793  5.940303  3.294395  2.755484 -1.331103 -2.437431  0.304749 -10.490963  
1794  1.756123  5.252211 -2.698683  6.156502  2.062131  0.333083  -8.650226  
1795  2.108555 -1.774974 -3.449632  1.169886  4.666940 -7.420535  -4.207070  
1796  2.016318 -2.897870 -1.242940  1.372061  0.816865 -3.805524  -6.572999  

[1797 rows x 64 columns]

In [12]:
var_frame = pd.DataFrame(PCA.var())

In [13]:
var_frame

0
PCA0   34.817348
PCA1   22.662658
PCA2   36.122943
PCA3   20.600772
PCA4   17.033394
...          ...
PCA59  22.005809
PCA60  14.972511
PCA61  27.389848
PCA62  18.936912
PCA63  34.189816

[64 rows x 1 columns]

In [14]:
name = var_frame.index
var = var_frame[0]

In [15]:
pca_var = list(zip(var, name))

In [16]:
pca_var.sort(reverse = True)

In [17]:
var, indices = zip(*(pca_var))

In [18]:
var

(40.23504900023399,
 36.122943117953916,
 34.81734838936,
 34.18981580895936,
 33.702806875623175,
 32.136769550693906,
 27.66526410293431,
 27.577685742066926,
 27.38984784411971,
 27.183153416930228,
 27.073901917342823,
 26.80102187331152,
 26.26347964734057,
 26.10171190492258,
 25.396511820416624,
 24.398711562615937,
 24.35386215519744,
 23.21783105539243,
 22.662658322552044,
 22.652903473772277,
 22.005808959384577,
 21.541689524562287,
 21.040801074429247,
 20.785423561438154,
 20.600772286411768,
 20.04885077808891,
 19.749761075388232,
 19.68416127047621,
 18.936911569564536,
 18.43375702705799,
 17.702605318249567,
 17.512101847149864,
 17.307862057730752,
 17.03339351334673,
 17.026675064201974,
 16.84637842586087,
 16.732582019277555,
 16.590634598045376,
 16.557372347571306,
 16.28106430678261,
 15.93195927425152,
 15.687373384586255,
 15.441383397620632,
 15.368851105282134,
 14.972511439044325,
 14.963830653099215,
 14.920529962192012,
 14.83571722847165,
 14.112993124

In [19]:
indices

('PCA23',
 'PCA2',
 'PCA0',
 'PCA63',
 'PCA17',
 'PCA41',
 'PCA33',
 'PCA31',
 'PCA61',
 'PCA47',
 'PCA27',
 'PCA14',
 'PCA38',
 'PCA48',
 'PCA5',
 'PCA58',
 'PCA46',
 'PCA49',
 'PCA1',
 'PCA13',
 'PCA59',
 'PCA56',
 'PCA25',
 'PCA51',
 'PCA3',
 'PCA42',
 'PCA50',
 'PCA52',
 'PCA62',
 'PCA12',
 'PCA19',
 'PCA18',
 'PCA35',
 'PCA4',
 'PCA37',
 'PCA10',
 'PCA32',
 'PCA24',
 'PCA6',
 'PCA43',
 'PCA9',
 'PCA30',
 'PCA22',
 'PCA15',
 'PCA60',
 'PCA54',
 'PCA21',
 'PCA44',
 'PCA26',
 'PCA45',
 'PCA53',
 'PCA7',
 'PCA36',
 'PCA20',
 'PCA28',
 'PCA29',
 'PCA57',
 'PCA34',
 'PCA11',
 'PCA55',
 'PCA39',
 'PCA16',
 'PCA40',
 'PCA8')

In [20]:
var = list(var)
sum_var = sum(var)
per_var = []
for i in range(len(var)):
    var[i] = var[i]/sum_var
    per_var.append(var[i])

In [21]:
per_var

[0.03346930547155247,
 0.030048672681852143,
 0.028962620846967976,
 0.02844061130184083,
 0.02803549558402205,
 0.026732795999696808,
 0.023013198646953267,
 0.022940347066418315,
 0.022784095138267485,
 0.022612157509389934,
 0.022521277246937792,
 0.02229428347464933,
 0.021847131913711116,
 0.021712566301863606,
 0.021125949468198083,
 0.02029593478056266,
 0.020258627046276095,
 0.019313625788682585,
 0.018851808387023564,
 0.01884369386941388,
 0.018305411836480805,
 0.01791933662282166,
 0.017502675304860354,
 0.01729024091729904,
 0.017136639763997753,
 0.01667752687567319,
 0.016428730742157196,
 0.01637416190319637,
 0.015752566326086632,
 0.015334019971577335,
 0.014725815421161245,
 0.014567346150561128,
 0.014397450398688822,
 0.014169135241069213,
 0.014163546535890312,
 0.014013567763300837,
 0.013918906844819544,
 0.013800828658756164,
 0.013773159637605437,
 0.013543314304961522,
 0.013252913192852243,
 0.01304945575813679,
 0.012844830332760824,
 0.012784494742046992,

In [22]:
cumvar = np.cumsum(per_var)

In [23]:
cumvar = list(cumvar)
for i in range(len(cumvar)):
    cumvar[i] = cumvar[i]*100
    cumvar.append(cumvar[i])
cumvar

[3.346930547155247,
 6.351797815340461,
 9.248059900037259,
 12.092121030221342,
 14.895670588623547,
 17.568950188593227,
 19.870270053288554,
 22.164304759930385,
 24.442714273757133,
 26.703930024696128,
 28.956057749389906,
 31.18548609685484,
 33.370199288225955,
 35.54145591841231,
 37.65405086523212,
 39.683644343288385,
 41.70950704791599,
 43.64086962678425,
 45.526050465486605,
 47.41041985242799,
 49.24096103607607,
 51.03289469835824,
 52.78316222884428,
 54.51218632057419,
 56.22585029697396,
 57.89360298454127,
 59.536476058756996,
 61.17389224907663,
 62.7491488816853,
 64.28255087884304,
 65.75513242095916,
 67.21186703601528,
 68.65161207588415,
 70.06852559999108,
 71.4848802535801,
 72.88623702991019,
 74.27812771439216,
 75.65821058026778,
 77.03552654402831,
 78.38985797452446,
 79.71514929380969,
 81.02009486962336,
 82.30457790289944,
 83.58302737710414,
 84.82850755292492,
 86.07326562231424,
 87.31442174741092,
 88.54852277163585,
 89.72250438650585,
 90.725961

In [24]:
for i in range(len(cumvar)):
    if (cumvar[i]>90):
        print(i)
        break

49


In [25]:
indices = indices[:50]

In [26]:
print('count:',len(indices))
print(indices)


count: 50
('PCA23', 'PCA2', 'PCA0', 'PCA63', 'PCA17', 'PCA41', 'PCA33', 'PCA31', 'PCA61', 'PCA47', 'PCA27', 'PCA14', 'PCA38', 'PCA48', 'PCA5', 'PCA58', 'PCA46', 'PCA49', 'PCA1', 'PCA13', 'PCA59', 'PCA56', 'PCA25', 'PCA51', 'PCA3', 'PCA42', 'PCA50', 'PCA52', 'PCA62', 'PCA12', 'PCA19', 'PCA18', 'PCA35', 'PCA4', 'PCA37', 'PCA10', 'PCA32', 'PCA24', 'PCA6', 'PCA43', 'PCA9', 'PCA30', 'PCA22', 'PCA15', 'PCA60', 'PCA54', 'PCA21', 'PCA44', 'PCA26', 'PCA45')
